### Importing Libraries

In [1]:
import numpy as np
import pandas as pd

### Reading the CSV File

In [2]:
sal = pd.read_csv('SalariesInSanFranciscoDataSet.csv')

C:\Users\USER\AppData\Local\Temp\ipykernel_6700\3184198875.py:1: DtypeWarning: Columns (0: BasePay, 1: OvertimePay, 2: OtherPay, 3: Benefits, 4: Status) have mixed types. Specify dtype option on import or set low_memory=False.
  sal = pd.read_csv('SalariesInSanFranciscoDataSet.csv')

### Selecting Head of the Dataset

In [3]:
sal.head(5)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.6,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.0,56120.71,198306.9,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.6,9737.0,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

### understanding the dataset

In [74]:
sal.info()

<class 'pandas.DataFrame'>
Index: 148650 entries, 0 to 148653
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148650 non-null  int64
 1   EmployeeName      148650 non-null  str
 2   JobTitle          148650 non-null  str
 3   BasePay           148650 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          148650 non-null  float64
 7   TotalPay          148650 non-null  float64
 8   TotalPayBenefits  148650 non-null  float64
 9   Year              148650 non-null  int64
 10  Agency            148650 non-null  str
 11  title_len         148650 non-null  int64
dtypes: float64(6), int64(3), str(3)
memory usage: 21.4 MB

### Cleaning the Dataset

In [9]:
new_sal = sal.drop(sal[sal['EmployeeName'] == 'Not provided'].index)

In [14]:
new_sal = new_sal.drop(new_sal[new_sal['JobTitle'] == 'Not provided'].index)

In [15]:
new_sal = new_sal.drop(new_sal[new_sal['BasePay'] == 'Not provided'].index)

In [35]:
new_sal.info()

<class 'pandas.DataFrame'>
Index: 148650 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148650 non-null  int64
 1   EmployeeName      148650 non-null  str
 2   JobTitle          148650 non-null  str
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148650 non-null  float64
 8   TotalPayBenefits  148650 non-null  float64
 9   Year              148650 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148650 non-null  str
 12  Status            38119 non-null   str
dtypes: float64(7), int64(2), str(4)
memory usage: 22.6 MB

In [34]:
new_sal[['BasePay','OvertimePay','OtherPay','Benefits']] = new_sal[['BasePay','OvertimePay','OtherPay','Benefits']].astype('float64')

In [50]:
new_sal.isna().sum()

Id                  0
EmployeeName        0
JobTitle            0
BasePay             0
OvertimePay         0
OtherPay            0
Benefits            0
TotalPay            0
TotalPayBenefits    0
Year                0
Agency              0
dtype: int64

In [38]:
new_sal['BasePay'] = new_sal['BasePay'].fillna(new_sal['BasePay'].mean())

In [46]:
new_sal['Benefits'] = new_sal['Benefits'].fillna(new_sal['Benefits'].median())

In [49]:
new_sal.drop(columns = ['Notes','Status'],inplace = True)

In [51]:
new_sal

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,28628.62,567595.43,567595.43,2011,San Francisco
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,28628.62,538909.28,538909.28,2011,San Francisco
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,28628.62,335279.91,335279.91,2011,San Francisco
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,28628.62,332343.61,332343.61,2011,San Francisco
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,28628.62,326373.19,326373.19,2011,San Francisco
...,...,...,...,...,...,...,...,...,...,...,...
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.00,0.00,0.00,2014,San Francisco
148647,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.00,0.00,0.00,2014,San Francisco
148648,148649,Leon Walker,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,San Francisco
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.00,0.00,0.00,2014,San Francisco
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.00,-618.13,-618.13,2014,San Francisco

In [52]:
sal = new_sal

In [54]:
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,28628.62,567595.43,567595.43,2011,San Francisco
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,28628.62,538909.28,538909.28,2011,San Francisco
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,28628.62,335279.91,335279.91,2011,San Francisco
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,28628.62,332343.61,332343.61,2011,San Francisco
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,28628.62,326373.19,326373.19,2011,San Francisco

In [53]:
sal.info()

<class 'pandas.DataFrame'>
Index: 148650 entries, 0 to 148653
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148650 non-null  int64
 1   EmployeeName      148650 non-null  str
 2   JobTitle          148650 non-null  str
 3   BasePay           148650 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          148650 non-null  float64
 7   TotalPay          148650 non-null  float64
 8   TotalPayBenefits  148650 non-null  float64
 9   Year              148650 non-null  int64
 10  Agency            148650 non-null  str
dtypes: float64(6), int64(2), str(3)
memory usage: 20.2 MB

### Average of BasePay

In [79]:
print(sal['BasePay'].mean())

66325.4488404877

### What is the Highest amount of OvertimePay in the Dataset

In [80]:
print(sal['OvertimePay'].max())

245131.88

### What is the Job Title of JOSEPH DRISCOLL

In [57]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: str

### How much does JOSEPH DRISCOLL make including (Benifits)

In [58]:
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

### What is the Highest Paid Person (including Benifits)

In [59]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].max()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,28628.62,567595.43,567595.43,2011,San Francisco

### What is the Lowest Paid Person(Including Benifits)

In [60]:
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()] # the record it incorrect because his total pay is in minus which in impossible.

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Agency
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,San Francisco

### What was the Average BasePay of all Employees per Year

In [61]:
sal.groupby('Year')['BasePay'].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69576.866579
2014    66564.421924
Name: BasePay, dtype: float64

### How Many Unique Job Titles are there

In [62]:
sal['JobTitle'].nunique()

2158

### What are the top most Common Jobs

In [82]:
sal['JobTitle'].value_counts().sort_values(ascending = False).head()

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

### How many Job titles were represented by only one person in 2013

In [64]:
print((sal[sal['Year'] == 2013]['JobTitle'].value_counts() == 1).sum())

202

### How Many people have word Chief in there Job title

In [73]:
print(sal['JobTitle'].str.contains('Chief').sum())

423

### IS there any Correlation between Length of job title string and TotalPayBenefits

In [66]:
sal['title_len'] = sal['JobTitle'].apply(lambda x: len(x))

In [67]:
sal[['title_len','TotalPayBenefits']].corr()

                  title_len  TotalPayBenefits
title_len           1.00000          -0.03692
TotalPayBenefits   -0.03692           1.00000